---
title: "Beer and Breweries Case Study"
author: "Matt Sherga & Rudranil Mitra"
date: "6/15/2020"
output: powerpoint_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r}
library(XML) #xml_Parse
library(dplyr)
library(tidyr)
library(stringr)
library(rvest) #html_table, html_node
library(ggplot2)
library(RCurl) #getURL
library(tidyverse)
library(BSDA)
library(GGally)
library(openintro)
#library(usmap) 
#devtools::install_github("wmurphyrd/fiftystater")
#library(fiftystater)
library(viridis)
library(mapproj)
library(ggpubr)

beers<- read.csv(file.choose(),na.strings=c("","NA"))
brews<- read.csv(file.choose(),na.strings=c("","NA"))
#get column names
colnames(beers)
colnames(brews)

#Q1 breweries per state
brewbystate<- data.frame(brews %>% group_by(State) %>% tally())

bbsplot<- brewbystate %>% ggplot(aes(x = as.factor(State), y = n)) + labs(y="# of Breweries", x = "State") + geom_bar(stat = "identity", position = "dodge", fill = "goldenrod3") + geom_label(size = 3, label = brewbystate$n, vjust = 1)




#Q2 merge the data sets and print first/last 6 rows.
#rename brewery id column to match "beers" respective column.
names(brews)[1] <- "Brewery_id"
#rename columns from each df since they are names for different things.
names(beers)[1]<- "Beer"
names(brews)[2]<- "Brewery"
#merge
brewerydata<- merge(beers,brews, by = "Brewery_id", all = TRUE)
brewerydata$State<-as.factor(brewerydata$State)
brewerydata$City<-as.factor(brewerydata$City)
brewerydata$Brewery_id<-as.factor(brewerydata$Brewery_id)
brewerydata$ABV<-brewerydata$ABV * 100
brewerydata<-brewerydata %>% rename("% ABV" = ABV)
head(brewerydata, 6)
tail(brewerydata, 6)



#Q3 Address the missing values
#how many na rows in ABV and IBU? What about missing Styles?
length(which(is.na(brewerydata$`% ABV`))) #62 NAs
length(which(is.na(brewerydata$IBU))) #1005 NAs
length(which(is.na(brewerydata$Style))) #5 NAs

#examined the five rows with View(brewerydata), and found that "CROWLER" is not a beer. It's just a container. "Can'd AID foundation" is also not a beer. It's a foundation. Special release just refers to a series of beers. add styles to Oktoberfest and kilt lifter.

#deleting crowler and can'd aid
brewerydata<-brewerydata[-c(227,992, 993),]

#adding style from https://untappd.com/b/freetail-brewing-co-oktoberfiesta/79567
brewerydata$Style[454] <- "Märzen"
#adding style from https://untappd.com/b/four-peaks-brewing-company-kilt-lifter/4055
brewerydata$Style[945] <- "Scottish Export Ale"

#find means per style of ABV and IBU, disregarding NA rows
abvmean <- brewerydata %>% group_by(Style, na.rm = TRUE) %>% mutate(`Mean%ABV` = round(mean(`% ABV`, na.rm=TRUE), digits = 1))

ibumean <- brewerydata %>% group_by(Style) %>% mutate(MeanIBU = as.integer(mean(IBU, na.rm = TRUE)))

#replace NA rows with means for their respective styles taken from above.
brewerydata$`% ABV`[is.na(brewerydata$`% ABV`)] <- abvmean$`Mean%ABV`[is.na(brewerydata$`% ABV`)]

brewerydata$IBU[is.na(brewerydata$IBU)] <- ibumean$MeanIBU[is.na(brewerydata$IBU)]

#52 empty IBU values remain. After looking at each one, there are three that have IBU values according to untappd.com. the rest do not have IBU because of their style.

#add IBU from https://untappd.com/b/thunderhead-brewing-golden-frau/38392
brewerydata$IBU[1476] <- 12
#add IBU from https://untappd.com/b/hawai-i-nui-brewing-southern-cross-belgian-double-red-ale/29698
brewerydata$IBU[1199] <- 59
#add IBU from https://untappd.com/b/figueroa-mountain-brewing-co-weiss-weiss-baby/1043342
brewerydata$IBU[273] <- 40


#Q4 Medians of ABV and IBU
#find median of non-NA IBUs by state
brewerydata<- brewerydata %>% group_by(State) %>% mutate(MedianIBU = median(IBU, na.rm = TRUE))
#find median of non-NA ABVs by state
brewerydata<- brewerydata %>% group_by(State) %>% mutate(MedianABV = median(`% ABV`, na.rm = TRUE))


####plot results####
#plot the median ABVs for each state, with labels
medabvplot<- brewerydata %>% ggplot(aes(x = State, y = MedianABV)) + ylab("Median % ABV") + geom_bar(stat = "identity", position = "dodge", fill = "goldenrod3") + geom_label(size = 3, label = brewerydata$MedianABV, vjust = 1)+ theme(plot.title = element_text(hjust = .5))+ labs(title = "Median %ABV per State")

#plot the median IBUs for each state, with labels
medibuplot<- brewerydata %>% ggplot(aes(x = State, y = MedianIBU), ylab = "Median IBU") + geom_bar(stat = "identity", position = "dodge", fill = "goldenrod3") + geom_label(size = 3, label = brewerydata$MedianIBU, vjust = 1)+ theme(plot.title = element_text(hjust = .5))+ labs(title = "Median IBU per State")

#plots both charts together in a stacked configuration
finalplot<- ggarrange(medabvplot, medibuplot, ncol = 1, nrow = 2)

#Q5

#Look up and store max values per state, making sure to ignore NA values
maxabvperstate<-brewerydata %>% group_by(State) %>% filter(`% ABV`==max(`% ABV`, na.rm = TRUE))
maxibuperstate<-brewerydata %>% group_by(State) %>% filter(IBU==max(IBU, na.rm = TRUE))
#discover which state has the highest for each
maxabvstate<-brewerydata$State[which.max(brewerydata$`% ABV`)] #Colorado (CO)
maxibustate<-brewerydata$State[which.max(brewerydata$IBU)] #Oregon (OR)

#plot max ABVs per state, label them, and call out the highest one
maxabvplot<- maxabvperstate %>% ggplot(aes(x = State, y = maxabvperstate$`% ABV`)) + ylab("Highest % ABV") + geom_bar(stat = "identity", position = "dodge", fill = "goldenrod3") + geom_label(size = 3, label = maxabvperstate$`% ABV`, vjust = 1)+ theme(plot.title = element_text(hjust = .5))+ labs(title = "Highest % ABV per State")+ geom_text(aes(8, 12.8, label="Colorado \n Highest Overall"))
#plot max IBUs per state, label them, and call out the highest one
maxibuplot<- maxibuperstate %>% ggplot(aes(x = State, y = IBU)) + ylab("Highest IBU") + geom_bar(stat = "identity", position = "dodge", fill = "goldenrod3") + geom_label(size = 3, label = maxibuperstate$IBU, vjust = 1)+ theme(plot.title = element_text(hjust = .5))+ labs(title = "Highest IBU per State")+ geom_text(aes(40, 138, label="Oregon \n Highest Overall"))

#plots both charts together in a stacked configuration
maxesfinalplot<- ggarrange(maxabvplot, maxibuplot, ncol = 1, nrow = 2)


#Q6 summary statistics and distribution of ABV
abvsum<-summary(brewerydata$`% ABV`)
#get data from the summary
abvsum<-data.frame(table(abvsum))
abvsum$stats[1]<- "Min"
abvsum$stats[2]<- "1st Q"
abvsum$stats[3]<- "Med"
abvsum$stats[4]<- "Mean"
abvsum$stats[5]<- "3rd Q"
abvsum$stats[6]<- "Max"
abvsum<-subset(abvsum, select = -c(Freq))
abvsum$abvsum<-round((as.numeric(as.character(abvsum$abvsum))), digits = 2)
sumstatsstr<-unlist(strsplit(toString(abvsum[1:6,1]), ", "))

abvplotdens<- brewerydata %>% ggplot(aes(x=`% ABV`)) + geom_density(aes(color = "red", size = 1)) + geom_histogram(aes(y=..density.., alpha = .2)) + labs(x = "% ABV", title = " Distribution of ABV Percentages", y = "Density") + theme(plot.title = element_text(hjust = .5), legend.position="none") + annotate("text", x = c(.1,5, 5.6, 5.97, 6.7, 12.8), y = .45, label = sumstatsstr)+ annotate("text", x = c(.1,5, 5.6, 5.97, 6.7, 12.8), y = .47, label = abvsum$stats )

abvplotbox<- brewerydata %>% ggplot(aes(x=`% ABV`)) + geom_boxplot() + labs(x = "% ABV", title = " Distribution of ABV Percentages") + theme(plot.title = element_text(hjust = .5), legend.position="none", axis.text.y = element_blank(), axis.title.y = element_blank(), axis.ticks.y = element_blank()) + annotate("text", x = c(.1,5, 5.6, 5.97, 6.7, 12.8), y = .4, label = sumstatsstr)+ annotate("text", x = c(.1,5, 5.6, 5.97, 6.7, 12.8), y = .43, label = abvsum$stats )+geom_point(aes(x=abvsum$abvsum[4], y=0), colour="red")


abvplots<- ggarrange(abvplotdens, abvplotbox, ncol = 1, nrow = 2)


#Q7 associate IBU and ABV on scatterplot


abvibuplot<-brewerydata %>% ggplot(aes(x= IBU, y = `% ABV`, color = `% ABV`)) + geom_point() + ylim(2.5, 13) + theme_dark() + stat_smooth(method = "lm", color = "red")

abvibuplot + scale_color_gradient(low = "gold2", high = "white")

#the relationship seems to indicate that generally, breweries are making higher % ABV beers with higher IBU. However, their is no dependency between the two variables since they are obtained through different means. ABV is determined by yeast amount and time to ferment, while IBU is a result of hops added.

#Q8 IBU/ABV for IPA vs any other Ales.
#subset the data to only Styles containing "Ale" and "IPA"
Ale_Data<- brewerydata[grepl("Ale|IPA", brewerydata$Style),]
#modify so we only have 2 levels for the KNN: "IPA" and "Other Ales"
BinaryTest<- Ale_Data
BinaryTest$Style<-ifelse(grepl("IPA", Ale_Data$Style), "IPA", "Other Ales")
BinaryTest$Style<- as.factor(BinaryTest$Style)
BinaryTest<-BinaryTest[, 4:6]
#KNN setup
library(class) #for the knn function
library(caret) #for the confusion matrix function
n.points<-nrow(BinaryTest)
normed1<- (BinaryTest[,1] - min(BinaryTest[,1]))/max(range(BinaryTest[,1]))
normed2<- (BinaryTest[,2] - min(BinaryTest[,2]))/max(range(BinaryTest[,2]))
normed<- data.frame(normed1, normed2)

set.seed(6)
beerloop<-data.frame()
for (k in 1:200) {
  predicted.labels <- knn.cv(normed, BinaryTest$Style, k) #predict values
  #how many were right, based on our known values saved above.
  num.correct.labels <- sum(predicted.labels == BinaryTest$Style)
  #correct div by total = accuracy.
  accuracy <- num.correct.labels / n.points
  CM<-confusionMatrix(table(BinaryTest$Style,predicted.labels))
  accuracy <- CM$overall[1]
  #add row to dataframe containing the values from each loop
  beerloop <- rbind(beerloop, data.frame(k, accuracy))
}

#what k has the highest accuracy? answer is 21 with .8964169
which(beerloop$accuracy == max(beerloop$accuracy))


cm<-knn.cv(normed, BinaryTest$Style, k = 21)
confusionMatrix(table(BinaryTest$Style, cm))




```

## Slide with Plot

```{r pressure}
plot(pressure)
```

